<a href="https://colab.research.google.com/github/PariAgrawal1234/Sequence_completion_LSTM_model/blob/main/Sequence_completion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from tensorflow import keras

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/qoute_dataset.csv")

In [ ]:
df.info()
df.isna().sum()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3038 entries, 0 to 3037
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   quote   3038 non-null   object
 1   Author  3038 non-null   object
dtypes: object(2)
memory usage: 47.6+ KB

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [ ]:
quote = df['quote']
quote = quote.str.lower()

In [ ]:
import string
translator = str.maketrans('', '', string.punctuation)
quote = quote.apply(lambda x: x.translate(translator))
quote

0       “the world as we have created it is a process ...
1       “it is our choices harry that show what we tru...
2       “there are only two ways to live your life one...
3       “the person be it gentleman or lady who has no...
4       “imperfection is beauty madness is genius and ...
                              ...
3033         the past beats inside me like a second heart
3034    damn claire warn a guy before you do a facepla...
3035    can you be a girl for a few secondsim always a...
3036    thats what fiction is for its for getting at t...
3037    if we have no peace it is because we have forg...
Name: quote, Length: 3038, dtype: object

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
vocab_size = 10000
tokenizer = Tokenizer(num_words = vocab_size)
tokenizer.fit_on_texts(quote)
word_indx = tokenizer.word_index
print(len(word_indx))
vocab_size = len(word_indx) + 1

8978

In [ ]:
seq = tokenizer.texts_to_sequences(quote)
print(seq[0:2])
print(quote[0:2])

[[713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809, 104, 752, 70, 2461], [947, 7, 70, 871, 373, 9, 433, 21, 19, 465, 14, 294, 52, 54, 70, 3676]]
0    “the world as we have created it is a process ...
1    “it is our choices harry that show what we tru...
Name: quote, dtype: object

In [ ]:
X = []
y = []

for sq in seq:
  for i in range(1, len(sq)):
    input_sq = sq[:i]
    output_sq = sq[i]
    X.append(input_sq)
    y.append(output_sq)

In [ ]:
max_len = max(len(x) for x in X)
max_len

745

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
X_padded = pad_sequences(X, maxlen=max_len, padding='pre')

X_padded = np.array(X_padded)
y = np.array(y)

In [ ]:
y.shape

(85271,)

In [ ]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y, num_classes = vocab_size)
y.shape

(85271, 8979)

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, LSTM, Embedding, SimpleRNN

embed_dim = 50
rnn_units = 128

rnn_model = Sequential([
    Embedding(vocab_size, embed_dim, input_length=max_len),
    SimpleRNN(rnn_units, return_sequences=False),
    Dense(vocab_size, activation='softmax')
])

rnn_model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
rnn_model.summary()

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
Lstm_model = Sequential([
    Embedding(vocab_size, embed_dim, input_length=max_len),
    LSTM(rnn_units, return_sequences=False),
    Dense(vocab_size, activation='softmax')
])

Lstm_model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
Lstm_model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
history_rnn = rnn_model.fit(X_padded, y, epochs=10, batch_size=128, validation_split=0.1, verbose = 1)

Epoch 1/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 52s 79ms/step - accuracy: 0.0287 - loss: 7.6639 - val_accuracy: 0.0376 - val_loss: 6.7677
Epoch 2/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.0429 - loss: 6.5748 - val_accuracy: 0.0509 - val_loss: 6.7198
Epoch 3/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.0360 - loss: 7.3352 - val_accuracy: 0.0360 - val_loss: 7.3177
Epoch 4/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.0460 - loss: 6.7582 - val_accuracy: 0.0442 - val_loss: 6.8990
Epoch 5/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 44s 73ms/step - accuracy: 0.0522 - loss: 6.4477 - val_accuracy: 0.0485 - val_loss: 6.8394
Epoch 6/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.0545 - loss: 6.3078 - val_accuracy: 0.0535 - val_loss: 6.8185
Epoch 7/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 69ms/step - accuracy: 0.0580 - loss: 6.1954 - val_accuracy: 0.0510 - val_loss: 6.8116
Epoch 8/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.0612 - loss: 6.0927 - val_accuracy: 0.0589 - val_loss: 6.8020
Epoch 9/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.0676 - loss: 5.9925 - val_accuracy: 0.0591 - val_loss: 6.7896
Epoch 10/10
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.0744 - loss: 5.8819 - val_accuracy: 0.0706 - val_loss: 6.7658

In [ ]:
history_lstm = Lstm_model.fit(X_padded, y, epochs=100, batch_size=128, validation_split=0.1, verbose = 1)

Epoch 1/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.1557 - loss: 4.8402 - val_accuracy: 0.1148 - val_loss: 6.5504
Epoch 2/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.1618 - loss: 4.7181 - val_accuracy: 0.1114 - val_loss: 6.6099
Epoch 3/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.1684 - loss: 4.5983 - val_accuracy: 0.1156 - val_loss: 6.6773
Epoch 4/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.1757 - loss: 4.4801 - val_accuracy: 0.1150 - val_loss: 6.7461
Epoch 5/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.1847 - loss: 4.3649 - val_accuracy: 0.1147 - val_loss: 6.8108
Epoch 6/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.1958 - loss: 4.2535 - val_accuracy: 0.1157 - val_loss: 6.8770
Epoch 7/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2083 - loss: 4.1443 - val_accuracy: 0.1144 - val_loss: 6.9617
Epoch 8/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.2224 - loss: 4.0403 - val_accuracy: 0.1133 - val_loss: 7.0403
Epoch 9/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.2359 - loss: 3.9410 - val_accuracy: 0.1112 - val_loss: 7.1147
Epoch 10/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.2498 - loss: 3.8454 - val_accuracy: 0.1142 - val_loss: 7.1787
Epoch 11/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.2643 - loss: 3.7550 - val_accuracy: 0.1114 - val_loss: 7.2716
Epoch 12/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.2765 - loss: 3.6724 - val_accuracy: 0.1103 - val_loss: 7.3455
Epoch 13/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 53ms/step - accuracy: 0.2883 - loss: 3.5936 - val_accuracy: 0.1100 - val_loss: 7.4282
Epoch 14/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3006 - loss: 3.5186 - val_accuracy: 0.1108 - val_loss: 7.4921
Epoch 15/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.3100 - loss: 3.4482 - val_accuracy: 0.1092 - val_loss: 7.5619
Epoch 16/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.3226 - loss: 3.3815 - val_accuracy: 0.1079 - val_loss: 7.6360
Epoch 17/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3315 - loss: 3.3154 - val_accuracy: 0.1066 - val_loss: 7.7137
Epoch 18/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3421 - loss: 3.2542 - val_accuracy: 0.1061 - val_loss: 7.7674
Epoch 19/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.3509 - loss: 3.1958 - val_accuracy: 0.1059 - val_loss: 7.8417
Epoch 20/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.3603 - loss: 3.1375 - val_accuracy: 0.1049 - val_loss: 7.9127
Epoch 21/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.3692 - loss: 3.0822 - val_accuracy: 0.1047 - val_loss: 7.9744
Epoch 22/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 53ms/step - accuracy: 0.3781 - loss: 3.0284 - val_accuracy: 0.1033 - val_loss: 8.0429
Epoch 23/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.3851 - loss: 2.9777 - val_accuracy: 0.1031 - val_loss: 8.1061
Epoch 24/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.3954 - loss: 2.9265 - val_accuracy: 0.1003 - val_loss: 8.1685
Epoch 25/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 55ms/step - accuracy: 0.4033 - loss: 2.8778 - val_accuracy: 0.1025 - val_loss: 8.2235
Epoch 26/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4119 - loss: 2.8303 - val_accuracy: 0.1024 - val_loss: 8.2897
Epoch 27/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.4194 - loss: 2.7843 - val_accuracy: 0.1030 - val_loss: 8.3492
Epoch 28/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.4272 - loss: 2.7397 - val_accuracy: 0.1001 - val_loss: 8.4210
Epoch 29/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4360 - loss: 2.6944 - val_accuracy: 0.1005 - val_loss: 8.4756
Epoch 30/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4435 - loss: 2.6542 - val_accuracy: 0.0981 - val_loss: 8.5175
Epoch 31/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4499 - loss: 2.6123 - val_accuracy: 0.0997 - val_loss: 8.5916
Epoch 32/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 53ms/step - accuracy: 0.4584 - loss: 2.5718 - val_accuracy: 0.0991 - val_loss: 8.6356
Epoch 33/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 52ms/step - accuracy: 0.4652 - loss: 2.5317 - val_accuracy: 0.0999 - val_loss: 8.7077
Epoch 34/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 52ms/step - accuracy: 0.4708 - loss: 2.4949 - val_accuracy: 0.0985 - val_loss: 8.7647
Epoch 35/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.4797 - loss: 2.4553 - val_accuracy: 0.0990 - val_loss: 8.8238
Epoch 36/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.4868 - loss: 2.4188 - val_accuracy: 0.0938 - val_loss: 8.8724
Epoch 37/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.4931 - loss: 2.3841 - val_accuracy: 0.0947 - val_loss: 8.9552
Epoch 38/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.4986 - loss: 2.3488 - val_accuracy: 0.0915 - val_loss: 8.9933
Epoch 39/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.5055 - loss: 2.3153 - val_accuracy: 0.0938 - val_loss: 9.0528
Epoch 40/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5115 - loss: 2.2818 - val_accuracy: 0.0940 - val_loss: 9.1050
Epoch 41/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5167 - loss: 2.2497 - val_accuracy: 0.0926 - val_loss: 9.1610
Epoch 42/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5236 - loss: 2.2177 - val_accuracy: 0.0918 - val_loss: 9.2293
Epoch 43/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.5296 - loss: 2.1865 - val_accuracy: 0.0909 - val_loss: 9.2789
Epoch 44/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5349 - loss: 2.1566 - val_accuracy: 0.0894 - val_loss: 9.3371
Epoch 45/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5426 - loss: 2.1263 - val_accuracy: 0.0888 - val_loss: 9.4079
Epoch 46/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.5461 - loss: 2.0965 - val_accuracy: 0.0881 - val_loss: 9.4527
Epoch 47/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5529 - loss: 2.0696 - val_accuracy: 0.0884 - val_loss: 9.5012
Epoch 48/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.5583 - loss: 2.0418 - val_accuracy: 0.0857 - val_loss: 9.5611
Epoch 49/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.5635 - loss: 2.0146 - val_accuracy: 0.0864 - val_loss: 9.6001
Epoch 50/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5688 - loss: 1.9867 - val_accuracy: 0.0869 - val_loss: 9.6748
Epoch 51/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 54ms/step - accuracy: 0.5718 - loss: 1.9618 - val_accuracy: 0.0881 - val_loss: 9.7044
Epoch 52/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5795 - loss: 1.9381 - val_accuracy: 0.0891 - val_loss: 9.7710
Epoch 53/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5836 - loss: 1.9112 - val_accuracy: 0.0877 - val_loss: 9.8306
Epoch 54/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5911 - loss: 1.8849 - val_accuracy: 0.0855 - val_loss: 9.8607
Epoch 55/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.5946 - loss: 1.8622 - val_accuracy: 0.0876 - val_loss: 9.9218
Epoch 56/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.5983 - loss: 1.8387 - val_accuracy: 0.0882 - val_loss: 9.9651
Epoch 57/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6029 - loss: 1.8152 - val_accuracy: 0.0868 - val_loss: 10.0110
Epoch 58/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6075 - loss: 1.7933 - val_accuracy: 0.0876 - val_loss: 10.0808
Epoch 59/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6124 - loss: 1.7698 - val_accuracy: 0.0862 - val_loss: 10.1256
Epoch 60/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6173 - loss: 1.7484 - val_accuracy: 0.0858 - val_loss: 10.1793
Epoch 61/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6225 - loss: 1.7268 - val_accuracy: 0.0869 - val_loss: 10.2316
Epoch 62/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 53ms/step - accuracy: 0.6262 - loss: 1.7064 - val_accuracy: 0.0841 - val_loss: 10.2901
Epoch 63/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6304 - loss: 1.6837 - val_accuracy: 0.0852 - val_loss: 10.3391
Epoch 64/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6344 - loss: 1.6651 - val_accuracy: 0.0823 - val_loss: 10.3930
Epoch 65/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6381 - loss: 1.6484 - val_accuracy: 0.0847 - val_loss: 10.4296
Epoch 66/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 54ms/step - accuracy: 0.6417 - loss: 1.6257 - val_accuracy: 0.0842 - val_loss: 10.4932
Epoch 67/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6475 - loss: 1.6063 - val_accuracy: 0.0820 - val_loss: 10.5339
Epoch 68/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6512 - loss: 1.5884 - val_accuracy: 0.0808 - val_loss: 10.5941
Epoch 69/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6537 - loss: 1.5691 - val_accuracy: 0.0836 - val_loss: 10.6329
Epoch 70/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6586 - loss: 1.5509 - val_accuracy: 0.0816 - val_loss: 10.6832
Epoch 71/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6620 - loss: 1.5335 - val_accuracy: 0.0834 - val_loss: 10.7336
Epoch 72/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.6665 - loss: 1.5161 - val_accuracy: 0.0824 - val_loss: 10.7701
Epoch 73/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 36s 60ms/step - accuracy: 0.6704 - loss: 1.4983 - val_accuracy: 0.0801 - val_loss: 10.8262
Epoch 74/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 68ms/step - accuracy: 0.6741 - loss: 1.4813 - val_accuracy: 0.0808 - val_loss: 10.8727
Epoch 75/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6766 - loss: 1.4653 - val_accuracy: 0.0814 - val_loss: 10.9212
Epoch 76/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.6809 - loss: 1.4481 - val_accuracy: 0.0794 - val_loss: 10.9674
Epoch 77/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.6848 - loss: 1.4324 - val_accuracy: 0.0803 - val_loss: 11.0107
Epoch 78/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 34s 56ms/step - accuracy: 0.6870 - loss: 1.4171 - val_accuracy: 0.0802 - val_loss: 11.0663
Epoch 79/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6909 - loss: 1.4012 - val_accuracy: 0.0808 - val_loss: 11.1113
Epoch 80/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6935 - loss: 1.3861 - val_accuracy: 0.0786 - val_loss: 11.1502
Epoch 81/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.6976 - loss: 1.3717 - val_accuracy: 0.0780 - val_loss: 11.1806
Epoch 82/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7012 - loss: 1.3552 - val_accuracy: 0.0802 - val_loss: 11.2247
Epoch 83/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7040 - loss: 1.3429 - val_accuracy: 0.0804 - val_loss: 11.2861
Epoch 84/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7076 - loss: 1.3282 - val_accuracy: 0.0795 - val_loss: 11.3122
Epoch 85/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7097 - loss: 1.3132 - val_accuracy: 0.0776 - val_loss: 11.3707
Epoch 86/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7143 - loss: 1.2994 - val_accuracy: 0.0775 - val_loss: 11.4176
Epoch 87/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7159 - loss: 1.2868 - val_accuracy: 0.0782 - val_loss: 11.4592
Epoch 88/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7195 - loss: 1.2748 - val_accuracy: 0.0796 - val_loss: 11.5181
Epoch 89/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 54ms/step - accuracy: 0.7220 - loss: 1.2596 - val_accuracy: 0.0795 - val_loss: 11.5472
Epoch 90/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7257 - loss: 1.2465 - val_accuracy: 0.0781 - val_loss: 11.5951
Epoch 91/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 33s 54ms/step - accuracy: 0.7268 - loss: 1.2358 - val_accuracy: 0.0772 - val_loss: 11.6367
Epoch 92/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7304 - loss: 1.2229 - val_accuracy: 0.0777 - val_loss: 11.6920
Epoch 93/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7335 - loss: 1.2101 - val_accuracy: 0.0794 - val_loss: 11.7338
Epoch 94/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7319 - loss: 1.2082 - val_accuracy: 0.0789 - val_loss: 11.7595
Epoch 95/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7359 - loss: 1.1928 - val_accuracy: 0.0767 - val_loss: 11.8175
Epoch 96/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 42s 54ms/step - accuracy: 0.7418 - loss: 1.1742 - val_accuracy: 0.0803 - val_loss: 11.8648
Epoch 97/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7441 - loss: 1.1629 - val_accuracy: 0.0786 - val_loss: 11.8984
Epoch 98/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 31s 52ms/step - accuracy: 0.7463 - loss: 1.1532 - val_accuracy: 0.0780 - val_loss: 11.9513
Epoch 99/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 32s 53ms/step - accuracy: 0.7489 - loss: 1.1417 - val_accuracy: 0.0765 - val_loss: 11.9877
Epoch 100/100
600/600 ━━━━━━━━━━━━━━━━━━━━ 41s 53ms/step - accuracy: 0.7509 - loss: 1.1308 - val_accuracy: 0.0765 - val_loss: 12.0248

In [ ]:
Lstm_model.save('/content/drive/MyDrive/Colab Notebooks/model_lstm.h5')
index_to_word = {}

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [ ]:
for word, index in word_indx.items():
  index_to_word[index] = word

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
from re import VERBOSE
def predictor(model, tokenizer, text_seq, max_len):
  text_seq = text_seq.lower()
  seq = tokenizer.texts_to_sequences([text_seq])
  seq = pad_sequences(seq, maxlen=max_len, padding='pre')

  pred = model.predict(seq, verbose = 0)
  pred_word_indx = np.argmax(pred)
  pred_word = index_to_word[pred_word_indx]

  return pred_word

In [ ]:
def generate_text(model, tokenizer, max_len, seed_text, n_words):
  text = []
  for _ in range(n_words):
    pred_word = predictor(model, tokenizer, seed_text, max_len)
    text.append(pred_word)
    seed_text = seed_text + ' ' + pred_word

  return ' '.join(text)

In [ ]:
seed = "The meaning of"
generate_text(Lstm_model, tokenizer, max_len, seed, 10)

'everyday life was i think about how you made them'

In [ ]:
import pickle
with open("tokenizer.pkl", "wb") as f:
  pickle.dump(tokenizer, f)

with open("max_len.pkl", "wb") as f:
  pickle.dump(max_len, f)

with open("index_to_word.pkl", "wb") as f:
  pickle.dump(index_to_word, f)